enum UserAnnotations { 
    ERROR_STRING =                "ERROR",
    PAGE_LOADED_STRING =          "CLIENT ENTERED",
    DEBUGGING_STRING =            "DEBUGGING",
    VALIDATING_STRING =           "VALIDATING",
    SERVER_FINISHED_STRING =      "FINISHED_SETUP",
    UNDEFINED_VARIABLE_STRING =   "UNDEFINED_VARIABLE",
    MERGE_POINT_STRING =          "MERGE_POINT",
    EVENT_HANDLER_END_STRING =    "EVENT_HANDLER_END"
};

export default UserAnnotations;